### ISSUE TITLE
Error Writing Links

### ISSUE THREAD

**Issue by Kickball** [JackFrancisD/pyApolloPhotosDownloader#2]
I'm getting the following error:

[_] Extracting direct links from page 140...
[_] Writing links to 'photolinks.lst'...
Traceback (most recent call last):
  File "script.py", line 120, in <module>
    main()
  File "script.py", line 114, in main
    writeLinksToFile()
  File "script.py", line 100, in writeLinksToFile
    file.write('\n'.join(finalLinksList))
TypeError: sequence item 0: expected str instance, list found

See [this reddit comment](https://www.reddit.com/r/DataHoarder/comments/3nej8i/a_python_script_that_downloads_all_nasas_apollo/cvwqqaq) for more details.

**Comment by Kickball** [comment]
This issue is fixed by using [this](https://github.com/JackFrancisD/pyApolloPhotosDownloader/blob/7b35e83b748ee2c3f70f0c45708dc799ac0d0be9/pyApolloDL.py) version of the script.

**Comment by JackFrancisD** [comment]
I unfortunately accepted a patch that I haven't tested. Sorry about that, now it's fixed.
